# Create clocks
create_clock -period 5.000 -name OSC_200MHz [get_ports OSC_200MHz]

create_clock -period 50000 -name clk20k [get_pins design_1_i/top_rtl_0/inst/slowclk/clk20k]
create_clock -period 3200000 -name clk_shift [get_pins design_1_i/top_rtl_0/inst/shiftclk/clock_out]
create_clock -period 100000.000 -name clk_pulse [get_pins design_1_i/top_rtl_0/inst/pulseclk/clock_out_reg_0]
create_clock -period 2500.000 -name clk_intrst [get_pins design_1_i/top_rtl_0/inst/resetclk/clock_out_reg_0]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# All IO on Z-turn are 3.3V fixed
set_property IOSTANDARD LVCMOS33 [get_ports opad_Ext_POR]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_I2C_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_I2C_scl_io]
# ClkSyncin in uta board
#set_property IOSTANDARD LVCMOS33 [get_ports OSC_200MHz]

set_property IOSTANDARD LVCMOS33 [get_ports opad_CLKin]
set_property IOSTANDARD LVCMOS33 [get_ports opad_CLKin2]
set_property IOSTANDARD LVCMOS33 [get_ports opad_DataIn]
set_property IOSTANDARD LVCMOS33 [get_ports opad_control]
set_property IOSTANDARD LVCMOS33 [get_ports opad_loadData]
set_property IOSTANDARD LVCMOS33 [get_ports opad_selDefData]
set_property IOSTANDARD LVCMOS33 [get_ports opad_serialOutCnt]
set_property IOSTANDARD LVCMOS33 [get_ports opad_startup]
set_property IOSTANDARD LVCMOS33 [get_ports opad_cal_control]
set_property IOSTANDARD LVCMOS33 [get_ports opad_DataOut1]
set_property IOSTANDARD LVCMOS33 [get_ports opad_DataOut2]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_cal_control]
set_property IOSTANDARD LVCMOS33 [get_ports TRIGGER]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_RST_EXT]
set_property IOSTANDARD LVCMOS33 [get_ports opad_RST_EXT]
set_property IOSTANDARD LVCMOS33 [get_ports opad_deltaT]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_deltaT]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_loadData]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_selDefData]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_serialOutCnt]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_startup]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_CLKin]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_CLKin2]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_DataIn]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_control]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_DataOut1]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_DataOut2]
set_property IOSTANDARD LVCMOS33 [get_ports opad_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports opad2_CLK]
# set_property IOSTANDARD LVCMOS33 [get_ports oTP1]
# set_property IOSTANDARD LVCMOS33 [get_ports oTP2]
set_property IOSTANDARD LVCMOS33 [get_ports i2c0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports i2c0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports oTP3]
set_property IOSTANDARD LVCMOS33 [get_ports oTP4]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLVDS[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports ExternalClkEnable]
#spi pins
#SCK
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_sck_io]
#SDI
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_io0_io]
# unassigned
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_io1_io]
#{bCS[0]}
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_ss_io]
#{bCS[1]}
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_ss1_o]
#unassigned
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_ss2_o]
set_property IOSTANDARD LVCMOS33 [get_ports bLDAC]
# these pins are in uta board but not in upenn
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_ID[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_ID[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports ClkSyncOut]
set_property IOSTANDARD LVCMOS33 [get_ports ClkSyncIn]

# From Nandor's schematic 18-Feb-2023
set_property PACKAGE_PIN T15 [get_ports opad_Ext_POR]
# Use default "i2c0" name for P15/16 -- the PS side conn. to unused pins

set_property PACKAGE_PIN M18 [get_ports FPGA_I2C_sda_io]
set_property PACKAGE_PIN K19 [get_ports FPGA_I2C_scl_io]

#ClkSyncOut in uta board is connected to Trigger 
set_property PACKAGE_PIN W13 [get_ports TRIGGER]
set_property PACKAGE_PIN E17 [get_ports opad2_RST_EXT]
set_property PACKAGE_PIN C20 [get_ports opad_RST_EXT]

set_property PACKAGE_PIN V10 [get_ports opad_CLKin]
set_property PACKAGE_PIN T10 [get_ports opad_CLKin2]
set_property PACKAGE_PIN T14 [get_ports opad_DataIn]
set_property PACKAGE_PIN U13 [get_ports opad_control]
set_property PACKAGE_PIN Y17 [get_ports opad_loadData]
set_property PACKAGE_PIN Y9  [get_ports opad_selDefData]
set_property PACKAGE_PIN Y8  [get_ports opad_serialOutCnt]
set_property PACKAGE_PIN B19 [get_ports opad_startup]
set_property PACKAGE_PIN V11 [get_ports opad_cal_control]
set_property PACKAGE_PIN V13 [get_ports opad_DataOut1]
set_property PACKAGE_PIN T11 [get_ports opad_DataOut2]
set_property PACKAGE_PIN U14 [get_ports opad2_cal_control]
#set_property PACKAGE_PIN Y6 [get_ports OSC_200MHz]#ClkSyncIn in uta board is connected to OSC_200MHz
#set_property PACKAGE_PIN H17 [get_ports ]
set_property PACKAGE_PIN Y16 [get_ports opad_deltaT]
set_property PACKAGE_PIN V12 [get_ports opad2_deltaT]
set_property PACKAGE_PIN J14 [get_ports {oLVDS[0]}]
set_property PACKAGE_PIN J16 [get_ports {oLVDS[1]}]
set_property PACKAGE_PIN L15 [get_ports {oLVDS[2]}]
set_property PACKAGE_PIN M14 [get_ports {oLVDS[3]}]
set_property PACKAGE_PIN K18 [get_ports {oLVDS[4]}]
set_property PACKAGE_PIN G18 [get_ports {oLVDS[5]}]
set_property PACKAGE_PIN H18 [get_ports {oLVDS[6]}]
set_property PACKAGE_PIN G20 [get_ports {oLVDS[7]}]
set_property PACKAGE_PIN P14 [get_ports opad2_loadData]
set_property PACKAGE_PIN R14 [get_ports opad2_selDefData]
set_property PACKAGE_PIN W14 [get_ports opad2_serialOutCnt]
set_property PACKAGE_PIN B20 [get_ports opad2_startup]
set_property PACKAGE_PIN Y14 [get_ports opad2_CLKin]
set_property PACKAGE_PIN V8 [get_ports opad2_CLKin2]
set_property PACKAGE_PIN U12 [get_ports opad2_DataIn]
set_property PACKAGE_PIN W8 [get_ports opad2_control]
set_property PACKAGE_PIN U15 [get_ports opad2_DataOut1]
set_property PACKAGE_PIN T12 [get_ports opad2_DataOut2]
set_property PACKAGE_PIN U7 [get_ports opad_CLK]
set_property PACKAGE_PIN T9 [get_ports opad2_CLK]
# set_property PACKAGE_PIN J18 [get_ports oTP1]
# set_property PACKAGE_PIN H18 [get_ports oTP2]
set_property PACKAGE_PIN P15 [get_ports i2c0_sda_io]
set_property PACKAGE_PIN P16 [get_ports i2c0_scl_io]
set_property PACKAGE_PIN G17 [get_ports oTP3]
set_property PACKAGE_PIN G19 [get_ports oTP4]
set_property PACKAGE_PIN F19 [get_ports {oLVDS[15]}]
set_property PACKAGE_PIN H15 [get_ports {oLVDS[14]}]
set_property PACKAGE_PIN J20 [get_ports {oLVDS[13]}]
set_property PACKAGE_PIN N15 [get_ports {oLVDS[12]}]
set_property PACKAGE_PIN J19 [get_ports {oLVDS[11]}]
set_property PACKAGE_PIN J18 [get_ports {oLVDS[10]}]
set_property PACKAGE_PIN L19 [get_ports {oLVDS[9]}]
set_property PACKAGE_PIN L20 [get_ports {oLVDS[8]}]

#set_property PULLUP true [get_ports i2c0_scl_io]
#set_property PULLUP true [get_ports i2c0_sda_io]


set_property PACKAGE_PIN F16 [get_ports ExternalClkEnable]

# --- SPI DAC UTA board mapping---
set_property PACKAGE_PIN F17 [get_ports SPI_0_sck_io]
set_property PACKAGE_PIN M17 [get_ports SPI_0_io0_io]
set_property PACKAGE_PIN L14 [get_ports SPI_0_io1_io]
set_property PACKAGE_PIN A20 [get_ports SPI_0_ss_io]
set_property PACKAGE_PIN D19 [get_ports SPI_0_ss1_o]
set_property PACKAGE_PIN M15 [get_ports SPI_0_ss2_o]
set_property PACKAGE_PIN D20 [get_ports bLDAC]


#these pins are in uta board not in upenn
set_property PACKAGE_PIN E18 [get_ports {FPGA_ID[0]}]
set_property PACKAGE_PIN E19 [get_ports {FPGA_ID[1]}]

set_property PACKAGE_PIN Y7 [get_ports ClkSyncOut]
set_property PACKAGE_PIN Y6 [get_ports ClkSyncIn]


#set_property PACKAGE_PIN L14 [get_ports {SHDN[0]}]
#set_property PACKAGE_PIN M15 [get_ports {SHDN[1]}]
#set_property PACKAGE_PIN K16 [get_ports {SHDN[2]}]
#set_property PACKAGE_PIN N16 [get_ports {SHDN[3]}]
#set_property PACKAGE_PIN K17 [get_ports {SHDN[4]}]
#set_property PACKAGE_PIN G19 [get_ports {SHDN[5]}]
#set_property PACKAGE_PIN G17 [get_ports {SHDN[6]}]
#set_property PACKAGE_PIN K14 [get_ports {SHDN[7]}]
#set_property PACKAGE_PIN L16 [get_ports {SHDN[8]}]
#set_property PACKAGE_PIN M19 [get_ports {SHDN[9]}]
#set_property PACKAGE_PIN H16 [get_ports {SHDN[10]}]
#set_property PACKAGE_PIN K19 [get_ports {SHDN[11]}]
#set_property PACKAGE_PIN G15 [get_ports {SHDN[12]}]
#set_property PACKAGE_PIN F20 [get_ports {SHDN[13]}]
#set_property PACKAGE_PIN K17 [get_ports {SHDN[14]}]
#set_property PACKAGE_PIN H17 [get_ports {SHDN[15]}]
